/*
 * Generated By SugarKubes Apr 14 2024
 */

const Monkey = require("../../models/Monkey");
/*
 * @oas [get] /monkey/{id}
 * summary: "get one monkey"
 * tags: ["monkey"]
 * parameters:
 *   - name: 'id'
 *     in: 'path'
 *     description: id of the monkey
 *     schema:
 *       type: 'string'
 *       example: "123456"
 * responses:
 *   "200":
 *     description: "get one monkey"
 *     schema:
 *       type: "Monkey"
 */
module.exports = async (req, res) => {
  try {
    const {
      id
    } = req.params;
    const existingMonkey = await Monkey.findOne({
      _id: id
    });
    if (!existingMonkey) throw new Error('monkey not found.');
    // @TODO handle safe area. Should be idempotent.

    // maybe with @sugar-safe-start
    // @sugar-safe-end

    return res.json({
      monkey: existingMonkey
    });

  } catch (e) {
    console.error('GetOne => monkey', e);
    return res.status(500).json({
      error: e.message ? e.message : e
    });
  }
};